# Generated by Django 5.1.2 on 2024-11-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categori',
        ),
    ]
