# Generated by Django 5.1.2 on 2024-11-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_order_numberphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
