# Generated by Django 5.1.2 on 2024-11-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_product_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
