# Generated by Django 5.1.2 on 2024-11-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_product_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='remaining_quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='purchased_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
