# Generated by Django 5.1.2 on 2024-11-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_order_date_order_alter_orderitem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
