# Generated by Django 5.1.2 on 2024-11-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_order_customer_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_origin',
            field=models.FloatField(default=0),
        ),
    ]
