# Generated by Django 5.1.2 on 2024-12-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
