# Generated by Django 5.1.2 on 2025-01-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productIdRecommend', models.IntegerField(default=0)),
            ],
        ),
    ]
