# Generated by Django 5.1.2 on 2025-01-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_recommendid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendid',
            name='productIdRecommend',
            field=models.IntegerField(),
        ),
    ]
